import { getDistance } from 'geolib'
import type { LatLng, LatLngExpression } from 'leaflet'
import ngeohash from 'ngeohash'

export function formatLatLng(
  latlng?: LatLng,
  options?: { decimals: number },
): string | undefined {
  if (!latlng) return undefined
  if (typeof options?.decimals === 'number') {
    return `${+latlng.lat.toFixed(options.decimals)}, ${+latlng.lng.toFixed(options.decimals)}`
  } else return `${latlng.lat}, ${latlng.lng}`
}

export const formatDistance = (distance: number): string => {
  if (distance < 0.05) {
    return Math.round(distance * 1000) + 'mm'
  }
  if (distance < 0.5) {
    return Math.round(distance * 100) + 'cm'
  }
  if (distance < 5) {
    // Distance in meters
    return `${distance.toFixed(1)}m`
  } else if (distance < 1000) {
    // Distance in meters
    return `${Math.round(distance)}m`
  } else {
    // Distance in kilometers
    const kilometers = distance / 1000
    if (kilometers < 100) {
      return `${kilometers.toFixed(1)}km`
    } else return `${Math.round(kilometers)}km`
  }
}

export const errorInDegreesToMeters = (location: {
  latitude: number
  error: { latitude: number; longitude: number }
}) => {
  const EARTH_RADIUS_KM = 6371 // Average radius of the Earth in kilometers
  const METERS_PER_DEGREE = (EARTH_RADIUS_KM * 1000 * Math.PI) / 180 // Approximate meters per degree of latitude

  // Calculate latitude error in meters
  const latErrorMeters = location.error.latitude * METERS_PER_DEGREE

  // Convert latitude to radians for longitude calculation
  const latInRadians = location.error.latitude * (Math.PI / 180)

  // Calculate longitude error in meters
  const lonErrorMeters =
    location.error.longitude * METERS_PER_DEGREE * Math.cos(latInRadians)

  return {
    latitude: latErrorMeters,
    longitude: lonErrorMeters,
  }
}

export const getRelevantGeohashes = ({
  coord,
  precision,
  rings,
}: {
  coord: LatLng
  precision: number
  rings: number
}) => {
  const geohashes = new Set<string>()
  geohashes.add(ngeohash.encode(coord.lat, coord.lng, precision))

  for (let i = 0, len = rings; i < len; ++i) {
    const nextghs = new Set<string>()
    for (const h of geohashes) {
      for (const n of ngeohash.neighbors(h)) {
        nextghs.add(n)
      }
    }
    for (const h of nextghs) {
      geohashes.add(h)
    }
  }

  return geohashes
}

export const getGeohashesInRadius = ({
  coord,
  radiusMeters,
  precision,
}: {
  coord: LatLng
  radiusMeters: number
  precision: number
}): Set<string> => {
  // Convert radius to degrees
  const latDelta = radiusMeters / 111320
  const lngDelta =
    radiusMeters / (111320 * Math.cos((coord.lat * Math.PI) / 180))

  // Bounding box
  const minLat = coord.lat - latDelta
  const maxLat = coord.lat + latDelta
  const minLng = coord.lng - lngDelta
  const maxLng = coord.lng + lngDelta

  // All geohashes in bounding box
  const geohashes = ngeohash.bboxes(minLat, minLng, maxLat, maxLng, precision)

  return new Set(geohashes)
}

/**
 * Get geohashes within radiusMeters from coord.
 * The geohashes fill the circle (i.e. they can overlap)
 *
 * This function has been generated by AI - claude-opus-4-6-thinking
 *
 * @param coord - latitude and longitude
 * @param radiusMeters - a radius from the coordinate, in metres
 * @param precision - geohash precision (length of returned geohashes)
 * @returns
 */
export const getCircleGeohashesInRadius = ({
  coord,
  radiusMeters,
  precision,
}: {
  coord: LatLng
  radiusMeters: number
  precision: number
}): Set<string> => {
  // Get geohash size to expand search area
  const sampleGh = ngeohash.encode(coord.lat, coord.lng, precision)
  const [sLat0, sLng0, sLat1, sLng1] = ngeohash.decode_bbox(sampleGh)
  const ghDiagonal = getDistance(
    { lat: sLat0, lng: sLng0 },
    { lat: sLat1, lng: sLng1 },
  )

  // Expand search radius to catch all potentially intersecting geohashes
  const expandedRadius = radiusMeters + ghDiagonal
  const latDelta = expandedRadius / 111320
  const lngDelta =
    expandedRadius / (111320 * Math.cos((coord.lat * Math.PI) / 180))

  const minLat = coord.lat - latDelta
  const maxLat = coord.lat + latDelta
  const minLng = coord.lng - lngDelta
  const maxLng = coord.lng + lngDelta

  const candidates = ngeohash.bboxes(minLat, minLng, maxLat, maxLng, precision)

  // Filter: keep if geohash bbox intersects circle
  return new Set(
    candidates.filter(gh => {
      const [ghMinLat, ghMinLng, ghMaxLat, ghMaxLng] = ngeohash.decode_bbox(gh)

      // Find closest point on geohash bbox to circle center
      const closestLat = Math.max(ghMinLat, Math.min(coord.lat, ghMaxLat))
      const closestLng = Math.max(ghMinLng, Math.min(coord.lng, ghMaxLng))

      // If closest point is within radius, geohash intersects circle
      return (
        getDistance(coord, { lat: closestLat, lng: closestLng }) <= radiusMeters
      )
    }),
  )
}

export const normalizeLng = (lng: number) =>
  (((lng % 360) - 180 * 3) % 360) + 180

export const geohash2polygon = (gh: string): LatLngExpression[] => {
  const [lat0, lng0, lat1, lng1] = ngeohash.decode_bbox(gh)
  return [
    [lat0, lng0],
    [lat0, lng1],
    [lat1, lng1],
    [lat1, lng0],
  ]
}
